from config import DECISION_TYPES
"""
INITIAL_RUN_NUMBER = 2
INITIAL_MODEL_VERSION = [30 for d_t in range(DECISION_TYPES)]
INITIAL_MEMORY_VERSION = [None for d_t in range(DECISION_TYPES)]
INITIAL_ITERATION = None """

INITIAL_RUN_NUMBER = None
INITIAL_MODEL_VERSION = [None for d_t in range(DECISION_TYPES)]
INITIAL_MEMORY_VERSION = [None for d_t in range(DECISION_TYPES)]
INITIAL_ITERATION = None 