from config import DECISION_TYPES
"""
INITIAL_RUN_NUMBER = None
INITIAL_MODEL_VERSION = None
INITIAL_MEMORY_VERSION = None
INITIAL_ITERATION = None 
"""
INITIAL_RUN_NUMBER = 0
INITIAL_MODEL_VERSION = 2
INITIAL_MEMORY_VERSION = 30
INITIAL_ITERATION = 30
