from config import DECISION_TYPES

INITIAL_RUN_NUMBER = None
INITIAL_MODEL_VERSION = [None for d_t in range(DECISION_TYPES)]
INITIAL_MEMORY_VERSION = [None for d_t in range(DECISION_TYPES)]
INITIAL_ITERATION = None 
"""
INITIAL_RUN_NUMBER = 5
INITIAL_MODEL_VERSION = [32 for d_t in range(DECISION_TYPES)]
INITIAL_MEMORY_VERSION = [65 for d_t in range(DECISION_TYPES)]
INITIAL_ITERATION = None """